export const AGREGAR_PRODUTO = 'AGREGAR_PRODUTO';
export const AGREGAR_PRODUTO_EXITO = 'AGREGAR_PRODUTO_EXITO';
export const AGREGAR_PRODUTO_ERROR = 'AGREGAR_PRODUTO_ERROR';


export const COMECAR_CARREGAR_PRODUTOS = 'COMECAR_CARREGAR_PRODUTOS';
export const CARREGAR_PRODUTOS_EXITO = 'CARREGAR_PRODUTOS_EXITO';
export const CARREGAR_PRODUTOS_ERROR = 'CARREGAR_PRODUTOS_ERROR';


export const OBTER_PRODUTO_ELIMINAR = 'OBTER_PRODUTO_ELIMINAR';
export const PRODUTO_ELIMINADO_EXITO = 'PRODUTO_ELIMINADO_EXITO';
export const PRODUTO_ELIMINADO_ERROR = 'PRODUTO_ELIMINADO_ERROR';